Repository elastic/ems-landing-page, pull requests merged in 2021-04, with the labels that each got.

#313 Allow configurable service name in header
  public/config.json
  public/js/components/app.js
  public/main.js
Labels: v7.13

#316 [v7.12] Update dependencies (#315)
  yarn.lock
Labels: backport

#317 [v7.11] Update dependencies (#315)
  yarn.lock
Labels: backport

#318 [v7.10] Update dependencies (#315)
  yarn.lock
Labels: backport

#319 [v7.9] Update dependencies (#315)
  yarn.lock
Labels: backport

#320 [v7.8] Update dependencies (#315)
  yarn.lock
Labels: backport

#321 [v7.7] Update dependencies (#315)
  yarn.lock
Labels: backport

#322 [v7.6] Update dependencies (#315)
  yarn.lock
Labels: backport

#323 [v7.4] Update dependencies (#315)
  yarn.lock
Labels: backport

#324 [v7.2] Update dependencies (#315)
  yarn.lock
Labels: backport

#325 [v7.0] Update dependencies (#315)
  yarn.lock
Labels: backport

#326 [v6.7] Update dependencies (#315)
  yarn.lock
Labels: backport

#327 [v6.6] Update dependencies (#315)
  yarn.lock
Labels: backport

#328 [v2] Update dependencies (#315)
  yarn.lock
Labels: backport

#331 [v7.13] Bump to EMS v7.13 (#329)
  .backportrc.json
  .ci/jobs/elastic+ems-landing-page+v7.13.yml
  package.json
  public/config.json
  public/js/components/app.js
  yarn.lock
Labels: backport

#334 Migrate to Elastic License v2
  ELASTIC-LICENSE.txt
  LICENSE.txt
  package.json
  public/js/components/app.js
  public/js/components/feature_table.js
  public/js/components/layer_details.js
  public/js/components/map.js
  public/js/components/table_of_contents.js
  public/main.js
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
Labels: v7.14
