Repository elastic/ems-landing-page, pull requests merged in 2022-02, with the labels that each got.

#403 Bump to EMS 8.2
  .ci/jobs/elastic+ems-landing-page+v8.2.yml
  package.json
  public/config.json
Labels: v8.2

#402 Publish 8.1 landing page
  .ci/jobs/elastic+ems-landing-page+v8.1.yml
  public/config.json
Labels: v8.1

#407 February updates
  .gitignore
  yarn.lock
Labels: dependencies, v8.1, v8.0, v8.2, v7.17

#412 [v7.15] February updates (#407)
  .gitignore
  yarn.lock
Labels: backport

#411 [v7.16] February updates (#407)
  .gitignore
  yarn.lock
Labels: backport

#410 [v7.17] February updates (#407)
  .gitignore
  yarn.lock
Labels: backport

#409 [v8.0] February updates (#407)
  .gitignore
  yarn.lock
Labels: backport

#406 [v8.1] Publish 8.1 landing page (#402)
  .ci/jobs/elastic+ems-landing-page+v8.1.yml
  public/config.json
Labels: backport

#414 [v8.2] February updates (#407)
  .gitignore
  yarn.lock
Labels: backport

#415 [v8.1] February updates (#407)
  .gitignore
  yarn.lock
Labels: backport
