Repository elastic/ems-landing-page, pull requests merged in 2022-10, with the labels that each got.

#452 Vector tiles from .dev when manifest query param is testing
  public/config.json
Labels: v7.17, v8.4, v8.5

#454 Update backport config to 8.5 and 8.6
  .backportrc.json
Labels: v8.5, v8.6

#453 Include a fullscreen control on the map
  public/js/components/map.js
  public/main.css
Labels: v8.5

#456 [v8.6] Getting our vector tiles from dev domain when manifest is set to testing (#452) | Update backport config to 8.5 and 8.6 (#454) | Set 8.4 as the root default (#455) | Include a fullscreen control on the map (#453)
  .backportrc.json
  .ci/jobs/defaults.yml
  public/config.json
  public/js/components/map.js
  public/main.css
Labels: backport

#458 Use desaturated map as the default
  public/js/components/app.js
Labels: v8.6

#459 [v8.6] Use desaturated map as the default (#458)
  public/js/components/app.js
Labels: backport
