Repository elastic/ems-landing-page, pull requests merged in 2022-05, with the labels that each got.

#431 Display format for File Layers
  public/js/components/layer_details.js
Labels: v8.2, v7.17, v8.3

#433 [v7.17] Add a badge with default format for FileLayers (#431)
  public/js/components/layer_details.js
Labels: backport

#437 [v8.4] Bump to 8.4.0 (#436)
  .backportrc.json
  .ci/jobs/elastic+ems-landing-page+v8.4.yml
  package.json
Labels: backport, v8.4

#438 [v8.3] Add a badge with default format for FileLayers (#431)
  public/js/components/layer_details.js
Labels: backport, v8.3

#434 [Spacetime] Custom languages
  package.json
  public/js/components/app.js
  public/js/components/customize_tms.js
  public/js/components/layer_details.js
  public/js/components/map.js
  public/js/components/table_of_contents.js
  public/main.css
  yarn.lock
Labels: v8.3

#439 [v8.4] [Spacetime] Custom languages (#434)
  package.json
  public/js/components/app.js
  public/js/components/customize_tms.js
  public/js/components/layer_details.js
  public/js/components/map.js
  public/js/components/table_of_contents.js
  public/main.css
  yarn.lock
Labels: backport
